name: Continuous Integration

on:
  push:
    branches:
      - 'devops-sre-engineer'
      - '!master'
env:
  image: nginx
  tag: 1.19

jobs:
  image_build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'devops-sre-engineer'
      - name: Docker version
        run: docker version
      - name: install docker scan    
        run: |
          mkdir -p ~/.docker/cli-plugins && \
          curl https://github.com/docker/scan-cli-plugin/releases/latest/download/docker-scan_linux_amd64 -L -s -S -o ~/.docker/cli-plugins/docker-scan &&\
          chmod +x ~/.docker/cli-plugins/docker-scan
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: Build and push Docker image
        run: |
          docker build . -t  clouddevopsworks/$image:$tag
          docker push clouddevopsworks/$image:$tag
      - name: docker scan  image
        continue-on-error: true
        run: |
          docker scan -f Dockerfile $image:$tag --accept-license --json